### ISSUE TITLE
关于选择哪一种默认实现

### ISSUE THREAD

**Issue by kizzoberon** [xkcoding/simple-http#2]
您好，在读过您的源码之后看到源码中已经配置了OkHttp3、Apache 的 HttpClient、hutool-http的依赖，那在引入此项目之后这几种依赖不就都会被引入了吗，没能理解这样的话优先级的作用在哪

**Comment by xkcoding** [comment]
在 pom.xml 里，依赖的 scope 是 provided 

所以不会引入，具体引入是看用户引入的哪个包，假设都引入了的话，我的代码也做了优先选择的策略，具体代码在这儿

https://github.com/xkcoding/simple-http/blob/master/src/main/java/com/xkcoding/http/HttpUtil.java#L42-L62

**Comment by kizzoberon** [comment]
谢谢您的回复，确实是这样，一开始没注意到 pom 中的 scope。

**Comment by xkcoding** [comment]
> 谢谢您的回复，确实是这样，一开始没注意到 pom 中的 scope。

不客气
